[package]
name = "sedgewick"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
rand = "0.8.4"
rb_tree = "0.5.0"
fnv = "1.0.3"
dashmap = "5.2.0"
rayon = "1.5.1"
itertools = "0.10.3"

